#+title: Aide Correction
#+LATEX_HEADER:\input{/home/fabien/alphabetagammadelta/parametre.tex}
#+OPTIONS: toc:nil
#+latex_class: koma-article
#+latex_class_options: [a4paper, 11pt, DIV=18]
#+property: header-args:lisp :exports both

* Objectif

Avoir une interface qui permette de m'aider pour la correction de contrôle.

J'aimerai notamment :

+ comptage des points
+ statistiques de réussite
+ grille de réussite pour chaque question ("propreté", "justification")
+ Détection automatique d'erreur systématique chez les élèves, pour les notifier
  efficacement.
+ exporter en csv pour analyser les données dans un tableur.

* Étape 1

** On définit l'ensemble des élèves dans une variable globale

Nous avons donc le code lisp suivant :
  #+begin_src lisp
(defparameter *classe* '((ABDOUNE Maxence)
                         (AGAMAKOU Axel)
                         (ATTYE Charlotte)
                         (BEMBA Séréna)
                         (BRESSY Jade)
                         (CALEJO Alex)
                         (CHARLES Maeva)
                         (CORREIA Joana)
                         (DE-LUISE Enzo)
                         (DE-PERCIN Kristopher)
                         (FOURDRINIER Thomas)
                         (GALLOY Ronan)
                         (GARRUZZO Rafael)
                         (GERMAIN Willem)
                         (GORSSE Clara)
                         (LABAYE Elodie)
                         (LEOCADIE Enzo)
                         (LEVI-VALENSI Margaux)
                         (MADAOUI Lyma)
                         (MAHROUG Walid)
                         (MARTIN Emma)
                         (MOUROU Aya)
                         (POUMAROUX Alyssia)
                         (PUPILLI Lola)
                         (RACON Kassidi)
                         (RAMTANI Cerina)
                         (RENZI Ambre)
                         (SAHNOUN Halima)
                         (SALEM Ibrahim)
                         (SALLENAVE Helene)
                         (SLIMANI Shirine)
                         (TRAN Matthieu)
                         (TRAORE Saïd)
                         (TSHISELEKA MUTETENU Justino)
                         (VAREILLE Mathieu)
                         (ZEKA Kerene)))
  #+end_src

  #+RESULTS:
  : *CLASSE*

  Avoir des cons-listes ou des listes ne changent pas grand chose à mon avis.
  Autant faire au plus simple avec des listes.

** Exemple

On peut parcourir l'ensemble des élèves par :
#+name: parcourir-les-eleves
#+begin_src lisp :results output
(loop for (nom prenom) in *classe* do
  (print nom)
  (princ prenom))

(format t "~%La classe comporte ~S élèves" (length *classe*))
#+end_src

#+RESULTS: parcourir-les-eleves
#+begin_example

ABDOUNE MAXENCE
AGAMAKOU AXEL
ATTYE CHARLOTTE
BEMBA SÉRÉNA
BRESSY JADE
CALEJO ALEX
CHARLES MAEVA
CORREIA JOANA
DE-LUISE ENZO
DE-PERCIN KRISTOPHER
FOURDRINIER THOMAS
GALLOY RONAN
GARRUZZO RAFAEL
GERMAIN WILLEM
GORSSE CLARA
LABAYE ELODIE
LEOCADIE ENZO
LEVI-VALENSI MARGAUX
MADAOUI LYMA
MAHROUG WALID
MARTIN EMMA
MOUROU AYA
POUMAROUX ALYSSIA
PUPILLI LOLA
RACON KASSIDI
RAMTANI CERINA
RENZI AMBRE
SAHNOUN HALIMA
SALEM IBRAHIM
SALLENAVE HELENE
SLIMANI SHIRINE
TRAN MATTHIEU
TRAORE SAÏD
TSHISELEKA MUTETENU
VAREILLE MATHIEU
ZEKA KERENE
La classe comporte 36 élèves
#+end_example

* Mise en forme des contrôle dans lisp

** Définition d'un contrôle.

Un contrôle est une évaluation qui comporte un certain nombre de *questions*.
Chaque question vérifie que l'élève sait faire un certain nombre de
*compétences*. Chaque compétences acquises rapporte un certain nombre de *points*.

Plusieurs pistes pour implémenter un contrôle dans lisp :
+ La programmation orientée objet.
+ Une liste de liste. On peut utiliser des clé voire des tableaux de hashage.

La solution la plus souple me paraît être la deuxième option. Je ne connais pas
assez les objets dans lisp pour m'y fier.

** Programmer un exemple de contrôle.

On définit au passage une fonction qui ajoute un contrôle à la liste des contrôles.

Définir une fonction qui ajoute un exercice a un contrôle est plus délicate,
puisque techniquement le contrôle en question n'est pas une variable globale. Je
repousse ça à plus tard.

La variable src_lisp[:exports code]{*controle-1*} contient deux exercices, le
premier contient deux questions, et le suivant qu'une seule.

#+name: ajouter-reset-controle
#+begin_src lisp :exports code
(defparameter *controles* '())

(defparameter *controle-1* '(
                             (
                                (:enonce "Combien vaut 1 + 1 ?" :competence (:calcul 1 :presentation 0.5))
                                (:enonce "Montrer que $\sqrt{2}$ est irrationnel." :competence (:demonstration 2 :proprete 1 :logique 1)))
                             (
                                 (:enonce "Démontre qu'une somme de vecteur est bien définie" :competence (:demonstration 2)))))

(defun ajouter-controle (controle)
    (append controle *controles*))

;; (defun ajouter-exercice (exercice controle)
;;     (setf controle (append exercice controle)))

(defun reset-controles ()
    (setf *controles '()))

(defparameter *question-test* '(:enonce "Citer une identité remarquable" :competence (:cours 1)))
(ajouter-controle *controle-1*)
#+end_src

#+RESULTS: ajouter-reset-controle
| (:ENONCE Combien vaut 1 + 1 ? :COMPETENCE (:CALCUL 1 :PRESENTATION 0.5))                   | (:ENONCE Montrer que $sqrt{2}$ est irrationnel. :COMPETENCE (:DEMONSTRATION 2 :PROPRETE 1 :LOGIQUE 1)) |
| (:ENONCE Démontre qu'une somme de vecteur est bien définie :COMPETENCE (:DEMONSTRATION 2)) |                                                                                                        |

** Accéder aux caractéristiques d'un contrôle

On souhaite accéder aux nombres de points de la première question. On définit
deux fonctions qui permettent d'accéder aux compétences d'une question d'un
contrôle, et une autre qui retourne le nombre de points associés à cette question.

On avait débuté par faire des accès «absolus» aux questions, mais ça sert à
rien. Les fonctions acceptent une liste qu'elles comprennent comme une question.
Beaucoup plus souple, et pas besoin de traîner des indices partout. On voit ça
notamment dans la ligne [[(ancien-indice)]].

#+begin_src lisp -n -r
;; (defun liste-competence-point-question (controle exercice question)
;;   (let ((question-selectionne (nth question (nth exercice controle))))
;;     (getf question-selectionne :competence)))

(defun liste-competences-points-question (question)
  (getf question :competence))

;; (defun nombre-point-question (controle exercice question)
;;   (let ((ensemble-competence (liste-competence-point-question controle exercice question)))
;;     (reduce '+ (remove-if-not 'numberp ensemble-competence))))

(defun nombre-points-question (question)
  "En donnant une question, retourne la somme des points associés aux compétences."
  (reduce '+ (remove-if-not 'numberp question)))

(defun nombre-points-controle (controle)
  (loop
    for exercice in controle
    sum (loop
            for question in exercice
            sum (nombre-points-question (liste-competences-points-question question)))))

;(nombre-point-question *controle-1* 0 0) (ref:ancien-indice)
(nombre-points-controle *controle-1*)
#+end_src

#+RESULTS:
: NOMBRE-POINT-CONTROLE

** Coder une interface pour ajouter un nouveau contrôle


* Macro

** Parcourir toutes les questions d'un contrôle

Une idée à peaufiner pour plus tard.

On notera qu'il peut y avoir des soucis à ne pas avoir utiliser ~gemsym~ pour le
nom d'une variable (ici exercice) qui parcourt les exercices.

Pour l'instant le code ne fonctionne pas.
#+begin_src lisp :eval no-export
(defmacro pour (question controle &body)
    `(loop
        for exercice in ,controle
            do
                (loop
                    for ,question in exercice
                        do
                            &body)))
#+end_src

* Corriger un contrôle

** KILL Chaque élève est assigné à une copie du contrôle
CLOSED: [2022-11-26 sam. 13:43]

Pour l'instant je ne sais pas créer une copie du modèle contrôle qui ne
contiennent que des compétences initialisée à $0$ sans modifier la liste des
compétences de chaque question.

J'ai testé de définir une liste des compétences pour chercher parmis elles, mais
dans ce cas on crée des propriétés pour celle qui n'y était pas, ce n'est pas ce
que l'on veut.

Une autre idée : une plist est une liste. Donc, on peut tout simplement tout
parcourir et mettre tous les nombres à 0.

Je suis en train d'implémenter cette idée dans la fonction ~reset-nombre-zero~
mais c'est pas si évident.

Le plan après c'est de :

- On parcourt chaque élève,
- On crée une copie blanche
- On parcourt la copie et on peut éditer les points
- On fait le résumé de cet élève et tout est enregistré à chaque étape pour
  éviter les pertes.

#+begin_src lisp
;; Il faudrait une copie neuve du contrôle
;; qui représente la copie de l'élève.

(defparameter *liste-competences* '(:calcul :raisonement :logique) "Liste des compétences d'une question.")

(defun reset-nombre-zero (liste)
  (let ((element (car liste)) (suite-vide? (cdr liste)))
    (cond
        ((numberp element) (progn
                                (setf element 0)
                                (unless suite-vide? (reset-nombre-zero (cdr liste)))))
        ((listp element) (reset-nombre-zero (car element))))))


(defun reset-notes (question)
  (loop)
  for competence in *liste-competences*
  do
  (let ((champ-competence (getf question :competence)))
      (when (getf champ-competence competence) (setf (getf champ-competence competence) 0))
      (print champ-competence))
  question)

(defun copie-eleve (controle)
  "Donne une copie viege du contrôle, prete à être corrigée"
  ;; C'est là que les objets aurait pu être utile...
  (loop)
  for exercice in controle
  collect (loop
              for question in exercice
                    (reset-notes (copy-list question))))
#+end_src

** DONE On reconstruit le contrôle pour chaque élève
CLOSED: [2022-11-26 sam. 14:36]

C'est bon, ça marche ENFIN
#+begin_src lisp
(defun copie-controle-competence-0 (controle)
  (when controle
    (cond
        ((getf controle :enonce) (afficher-question controle)) ;;Si ça a un énoncé, alors c'est une question
        ((listp controle) (cons (copie-controle-competence-0 (car controle)) (copie-controle-competence-0 (cdr controle)))) ;;Sinon si c'est une liste, c'est un exercice
        ((numberp controle) (read))
        (t controle)))) ;;Sinon, c'est la structure du controle
#+end_src

#+RESULTS:
: COPIE-CONTROLE-COMPETENCE-0

** On commence la correction

On pourrait mixer attribuer-point avec copie-controle-competence-0 : pour
attribuer des points, on reconstruit le contrôle !
#+begin_src lisp
(defun afficher-question (question)
  (print (getf question :enonce))
  (print "Les points sont répartis selon les compétences suivantes :")
  (print (getf question :competence)))

#+end_src

#+RESULTS:
: AFFICHER-QUESTION

* Commandes pour faciliter la correction

** En vrac

+ search pour chercher un élève dans la liste, et le sélectionner pour modifier
  ses notes
+ stat pour sortir les statistiques par questions du contrôle

*
